# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Graph-Layout-Aesthetic
version:      0.12
version_from: lib/Graph/Layout/Aesthetic.pm
installdirs:  site
requires:
    Test::More:                    0.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
